Pet.create(name: 'Max', age: '1', description: 'Loves to sleep')
Pet.create(name: 'Nala', age: '4', description: 'Loves to eat')
Pet.create(name: 'Simba', age: '4', description: 'Loves to play')
Pet.create(name: 'Leroy', age: '3', description: 'Loves to chill')
Pet.create(name: 'Jenkins', age: '2', description: 'Loves to party')